### ISSUE TITLE
Logging edit history for labNote

### ISSUE THREAD

**Issue by hngskj** [labnote-ant/labnote#131]
Actions: Create, Delete, Edit, Upload (image, table)
The timestamp will be marked at the end of the log message.

## Templates:
1. Experiment
   1) Column
      - Create: User created a new column.
      - Delete: User deleted `asdf` column.
      - Edit: User renamed the `asdf` column to `fdsa`.
   2) Task
      - Create: User created a new `[Chemical/Process/Memo]` in `asdf` column.
      - Delete: User deleted `[Chemical/Process/Memo]` in `asdf` column.
      - Edit: User edited `qwer` to `1234` of `zxcv` `[Chemical/Process/Memo]` in `asdf` column.
      - Upload: User uploaded an image to `zxcv` `Memo` in `asdf` column.
2. Result
   1) Data
      - Create: User created a new data.
      - Delete: User deleted `poiu` data.
      - Edit: User renamed the `poiu` data to `uiop`.
   2) Datum
      - Create: User created a new comment in `poiu` data.
      - Delete: User deleted `lkjh` comment in `poiu` data.
      - Edit: User edited `lkjh` to `hjkl` in `poiu` data.
      - Upload: User uploaded a `[image/table]` in `poiu` data.

Example: User edited `state` to `solution` of `Acetaminophen` `Chemical` in `Final step` column. `(8/18/2020, 4:13:10 PM)`

**Comment by jngynchoi** [comment]
It seems to be right.

All things are good when the location, where the action occurred, is marked.(In the lab/institute/company/etc. or outside the lab/institute/company/etc.)

**Comment by hngskj** [comment]
https://redux.js.org/advanced/middleware#understanding-middleware
https://github.com/LogRocket/redux-logger
https://egghead.io/lessons/javascript-redux-wrapping-dispatch-to-log-actions

**Comment by hngskj** [comment]
> It seems to be right.
> 
> All things are good when the location, where the action occurred, is marked.(In the lab/institute/company/etc. or outside the lab/institute/company/etc.)

Do we need the user's precise location like `서울 서초구 명달로 92` or just `inside/outside`?
The latter might be possible to check that the labnote is edited in the lab depending on the user's IP address.
If we got IP address of the lab beforehand.
