### ISSUE TITLE
Make upload function

### ISSUE THREAD

**Issue by hngskj** [labnote-ant/labnote#17]
Upper right corner, the upload button will be created.
When it is clicked, the current state, `localStorage`, will be sent to the servers.

**Comment by hngskj** [comment]
f2297a0c536e6af70dcfd01721750212de8a73be

**Comment by hngskj** [comment]
3505e7daf64134fb5fe4c8c1ddd6dccb1e62041e

**Comment by hngskj** [comment]
Now we have `server` branch.

**Comment by hngskj** [comment]
Make the `Analysis` button next to the `Load` button and popup window.

**Comment by hngskj** [comment]
9dd776237ade64cbeb452901361a68c2fc3de9a9

**Comment by hynchl** [comment]
done😊
