### ISSUE TITLE
Autocomplete chemical name or formula

### ISSUE THREAD

**Issue by jngynchoi** [labnote-ant/labnote#35]
When the user inputs chemical name, chemical name has to be autocomplete and vice versa.

**Comment by hngskj** [comment]
It seems like a more extended name size is not the solution.
I am considering adding a formula input field.

**Comment by hngskj** [comment]
Display name and formula for each ingredient
https://github.com/labnote-ant/labnote/issues/62#issuecomment-623276169

**Comment by hngskj** [comment]
https://github.com/labnote-ant/labnote/issues/46
