### ISSUE TITLE
How to show Chemicals in Process view

### ISSUE THREAD

**Issue by sl2820** [labnote-ant/labnote#80]
How do we show chemicals in Process view? 
Chemicals contain time-related information (like their amounts) or can be some sort of compounds (like mixed, injected, or added ones). 

Right now, we are just showing all the previously created chemicals. Like the below image example:
![image](https://user-images.githubusercontent.com/17037995/81184975-fcd31580-8feb-11ea-86d7-499fc9b55a31.png)
Above three red circled chemicals are technically the same chemicals, but later ones have gone through different processes (like heating and water bathing).

How can we create logic to show these chemicals?

**Comment by jngynchoi** [comment]
I think that's enough processes which chemical went through are showed.

In the above image, 'my name' and 'hello' are nicknames, right?

In that case, I think 'PSSS + NaBH4' needs to change to 'PSSS + my name'.

When the user input the nickname of the chemical, the chemical need to be showed in the nickname.

**Comment by hngskj** [comment]
Yup, those are nicknames.
That is possible to be implemented in this version.

However, after the next major updates, there will be some issues like:
1. Create Chem 1 (name: "PSSS", nickname: null)
2. Create Chem 2 (name: "AgNO3", nickname: null)
3. Set nickname Chem 1 (name: "PSSS", nickname: "hello")
4. Create Mix 1 (input: ["hello", "AgNO3"])
5. Output Chem 3 (name: "hello+AgNO3", nickname: null)
6. Change nickname Chem 1 (name: "PSSS", nickname: "world")
7. Open Mix 1 (input: ["world", "AgNO3", "hello+AgNO3"])

**Chem 1 is updated, but Chem 3 is not updated (name: "hello+AgNO3", nickname: null)**

**Comment by jngynchoi** [comment]
In that case, I think Chem 3 needs to be changed to "hello+world".

After 6. Change nickname Chem 1, all processes and chemicals including Chem1 need to update.

**Comment by hngskj** [comment]
Isn't Chem 3 name supposed to be "world+AgNO3"? 
Anyway, I get it. If that's the case, we need more discussion.
The output chemical from a process is not referencing previous chemicals, meaning that it's literally copy-and-paste the information of previous chemicals.
In my mind, there are two ways to implement: working with referencing or not. And the former seems to be more make sense to me.

**Comment by hngskj** [comment]
It is implemented with the new data structure.
